name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      - run: deno fmt --check
      - run: deno lint
      - run: deno cache --reload main.js
      - run: cd test && deno cache --reload test.js
      - run: cd test && deno task test

